# Generated by Django 5.0.2 on 2024-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_detail', models.TextField()),
                ('address', models.TextField()),
                ('on_time_del_rate', models.FloatField()),
                ('avg_quality_rating', models.FloatField()),
                ('avg_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
        ),
    ]
