# Generated by Django 5.0.2 on 2024-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='avg_quality_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='avg_response_time',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_del_rate',
            field=models.FloatField(blank=True),
        ),
    ]
