# Generated by Django 5.0.2 on 2024-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0002_alter_vendor_avg_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='avg_quality_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='avg_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_del_rate',
            field=models.FloatField(null=True),
        ),
    ]
