# Generated by Django 5.0.2 on 2024-04-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0004_alter_vendor_avg_quality_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('del_date', models.DateTimeField()),
                ('items', models.JSONField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Compeleted', 'Compeleted'), ('Canceled', 'Canceled')], max_length=50)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('ack_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VendorManagmentApi.vendor')),
            ],
        ),
    ]
