# Generated by Django 5.0.2 on 2024-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0006_vendor_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=50),
        ),
    ]
