# Generated by Django 5.0.2 on 2024-05-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0008_remove_purchase_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='ack_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='del_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendor_performance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
