# Generated by Django 5.0.2 on 2024-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0011_alter_purchase_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='ack_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
