# Generated by Django 5.0.2 on 2024-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0012_alter_purchase_order_ack_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_performance',
            name='on_time_del_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
