# Generated by Django 5.0.2 on 2024-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorManagmentApi', '0013_vendor_performance_on_time_del_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_performance',
            name='avg_quality_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_performance',
            name='avg_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_performance',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
